# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 5

#stages:
#  - build
#  - deploy

#cache:
#  key: ${CI_JOB_NAME}
#  paths:
#    - $CI_PROJECT_DIR/data/

before_script:
  - echo "Before script section"
  - git config --global user.email "4593890-MypDNS@users.noreply.gitlab.com"
  - git config --global user.name "MypDNS"
  - echo "CPU's" && lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('

after_script:
  - echo "After script section"
  - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
  - git remote set-url origin "https://gitlab-ci-token:${DEPLOY_KEY}@${url_host}"
  #- git remote set-url origin https://git:$MypDNS_CI@gitlab.com/$CI_PROJECT_PATH.git
  - git add .
  - git status
  - git commit -m '[skip ci] commit from CI runner'
  - git push "https://${GITLAB_USER_NAME}:${DEPLOY_KEY}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}"
  #- git push -u origin "${CI_COMMIT_BRANCH}"

build:
  #parallel: 3
  stage: build
  script:
    - echo "Building"
    - git checkout -B "${CI_COMMIT_BRANCH}"
    - bash $CI_PROJECT_DIR/scripts/import.sh
    - bash $CI_PROJECT_DIR/scripts/update_active_lists.sh

#test1:
#  stage: test
#  script:
#    - echo "Do a test here"
#    - echo "For example run a test suite"
#  only:
#   - merge_requests

#test2:
#  stage: test
#  script:
#    - echo "Do another parallel test here"
#    - echo "For example run a lint test"
#  only:
#   - merge_requests

#deploy:
#  stage: deploy
#  script:
#    - echo "Do your deploy here"
    #- git checkout -B master
#  only:
#  - mater

#  artifacts:
#    paths:
#    - data/
#  only:
#  - master
