# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 10

stages:
  - build
  - deploy

cache:
  key: ${CI_JOB_NAME}
  paths:
    - $CI_PROJECT_DIR/data/

before_script:
  - echo "Before script section"
  #- echo "PWD "
  #- bash -c "pwd"
  #- echo $CI_BUILDS_DIR
  #- echo $CI_PROJECT_DIR
  #- mkdir -p ~/.ssh
  #- eval $(ssh-agent -s)
  #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  #- echo "$id_rsa" | tr -d '\r' > ~/.ssh/id_rsa
  #- chmod 600 ~/.ssh/id_rsa
  #- ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
  #- git config --global user.email "3728965-spirillen@users.noreply.gitlab.com"
  #- git config --global user.name "$GITLAB_USER_LOGIN"
  #- git config --global user.email "git@gitlab.com"
  #- git config --global user.name "Gitlab CI"
  - git config --global user.email "4593890-MypDNS@users.noreply.gitlab.com"
  - git config --global user.name "MypDNS"

after_script:
  - echo "After script section"
  #- git remote set-url origin https://git:$DEPLOY_KEY@gitlab.com/$CI_PROJECT_PATH.git
  - git remote set-url origin https://git:$MypDNS_CI@gitlab.com/$CI_PROJECT_PATH.git
  - git add .
  - git add -f data/
  - git status
  - git commit -S -m '[skip ci] commit from CI runner'
  - git push -u origin master

build:
  #parallel: 3
  stage: build
  script:
    - echo "Building"
    - git checkout -B master
    - bash $CI_PROJECT_DIR/scripts/import.sh
    - bash $CI_PROJECT_DIR/scripts/update_active_lists.sh

#test1:
#  stage: test
#  script:
#    - echo "Do a test here"
#    - echo "For example run a test suite"
#  only:
#   - merge_requests

#test2:
#  stage: test
#  script:
#    - echo "Do another parallel test here"
#    - echo "For example run a lint test"
#  only:
#   - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Do your deploy here"
    #- git checkout -B master
  only:
  - mater

  artifacts:
    paths:
    - data/
  only:
  - master
