# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: ubuntu:disco
image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 10

#cache:
#  paths:
#    - data/*.list

before_script:
  - echo "Before script section"
  - mkdir -p ~/.ssh
  - echo "$SSH" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
  - git remote set-url origin https://"$GIT_CI_USER:$GIT_CI_PASS"@gitlab.com/$CI_PROJECT_PATH.git
  #- git remote set-url origin git@gitlab.com:$CI_PROJECT_PATH.git
  - git config --global user.email '$GITLAB_USER_EMAIL'
  - git config --global user.name '$GITLAB_USER_LOGIN'

after_script:
  - echo "After script section"
  - bash -c "ls -lha '$CI_PROJECT_DIR'/data/"
  - git checkout -B master
  - git add data/
  - git commit -m '[skip ci] commit from CI runner'
  - git push origin master

build1:
  #parallel: 3
  stage: build
  script:
    - bash scripts/import.sh

#test1:
#  stage: test
#  script:
#    - echo "Do a test here"
#    - echo "For example run a test suite"

#test2:
#  stage: test
#  script:
#    - echo "Do another parallel test here"
#    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  artifacts:
    paths:
    - data/
