# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 10

stages:
  - build
  - deploy

cache:
  paths:
    - data/*.list

before_script:
  - echo "Before script section"
  - echo "PWD "
  - bash -c "pwd"
  - echo $CI_BUILDS_DIR
  - echo $CI_PROJECT_DIR
  #- mkdir -p ~/.ssh
  #- eval $(ssh-agent -s)
  #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  #- echo "$id_rsa" | tr -d '\r' > ~/.ssh/id_rsa
  #- chmod 600 ~/.ssh/id_rsa
  #- ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
  #- git config --global user.email "3728965-spirillen@users.noreply.gitlab.com"
  #- git config --global user.name "$GITLAB_USER_LOGIN"
  - git config --global user.name "Gitlab-CI"

after_script:
  - echo "After script section"
  - git remote set-url origin https://Gitlab-CI:$SSH@gitlab.com/$CI_PROJECT_PATH.git
  - git status
  - git add .
  - git status
  - git commit -m '[skip ci] commit from CI runner'
  - git push -u origin master

build:
  #parallel: 3
  stage: build
  script:
    - echo "Building"
    - git checkout -B master
    - bash scripts/import.sh

#test1:
#  stage: test
#  script:
#    - echo "Do a test here"
#    - echo "For example run a test suite"

#test2:
#  stage: test
#  script:
#    - echo "Do another parallel test here"
#    - echo "For example run a lint test"

deploy:
  stage: deploy
  script:
    - echo "Do your deploy here"
    #- git checkout -B master

  artifacts:
    paths:
    - data/
