name: Update external sources

# Controls when the action will run. 
on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "54 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_NAME: "${{ secrets.GIT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  scheduler:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install requirements
        run: |
          sudo bash "${{ github.workspace }}/scripts/dependencies.sh"

      - name: Download and convert dumb hosts to plain data
        run: bash "${{ github.workspace }}/scripts/import.sh"

      - name: Update active list
        run: bash "${{ github.workspace }}/scripts/update_active_lists.sh"

      - name: Commit changes
        uses: actions/checkout@main # Yet another american...
        run: |
          tag=$(date +'day: %j of year %Y %H:%M:%S')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Committed new lists $tag" -a
          git pull --rebase
          git push
