name: Update external sources

# Controls when the action will run. 
on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "54 */4 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_NAME: "Spirillen"
  GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  scheduler:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install requirements
        run: |
          sudo bash "${{ github.workspace }}/scripts/dependencies.sh"

      - name: Download and convert dumb hosts to plain data
        run: bash "${{ github.workspace }}/scripts/import.sh"

      - name: Update active list
        run: bash "${{ github.workspace }}/scripts/update_active_lists.sh"

      - name: Commit changes
        run: |
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          git commit -m "Committed new lists" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Release Scheduler
        uses: koj-co/release-scheduler@master
        with:
          milliseconds: 1000
